id: PF3E6088F
initial_creation_type: input
source_metadata:
  Title: Āryaśālistamba sutra kātikā
  Editor: Sonam Rabten
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '2004'
  Āryaśālistambakamahāyānasūtraṭīkā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:52:52.018558'
last_modified_at: '2022-03-08T16:52:52.018567'
